spring:
  application:
    name: proxy-server

server:
  port: 8762

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    video-service:
      stripPrefix: false
      path: /video-service/**
      serviceId: video-service